name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull  # fetch actual LFS files

      - name: List data folder
        run: |
          ls -lh data

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.4
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker authentication
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/e-cercise-recommend-service" && \
             docker build -t "$IMAGE_NAME:$GITHUB_SHA" . && \
             docker push "$IMAGE_NAME:$GITHUB_SHA"
      
      - name: Write env.yaml
        run: |
          echo "BACKEND_URL: \"${{ secrets.BACKEND_URL }}\"" > env.yaml
          echo "RECOMMENDER_PORT: \"${{ secrets.RECOMMENDER_PORT }}\"" >> env.yaml
          echo "ALLOWED_ORIGINS: \"${{ secrets.ALLOWED_ORIGINS }}\"" >> env.yaml
          echo "DEBUG: \"${{ secrets.DEBUG }}\"" >> env.yaml
        
      - name: Deploy to Google Cloud Run with Secrets
        run: |
          gcloud run deploy e-cercise-recommend-service \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/e-cercise-recommend-service:$GITHUB_SHA \
            --platform=managed \
            --region=asia-southeast1 \
            --allow-unauthenticated \
            --memory=2Gi \
            --port=8080 \
            --env-vars-file=env.yaml
